//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YayineviYonetimSistemi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitaplar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kitaplar()
        {
            this.Yazarlar = new HashSet<Yazarlar>();
        }
    
        public int kitapID { get; set; }
        public string Baslik { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public Nullable<int> ISBN { get; set; }
        public Nullable<int> yayineviID { get; set; }
    
        public virtual Yayinevleri Yayinevleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yazarlar> Yazarlar { get; set; }
    }
}
